# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pr: none
trigger:
  tags:
    include:
      - DEV_*
      - RC_*

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: 'macOS-10.15'

variables:
  GIT_BRANCH: $(Build.SourceBranch)

steps:
- script: gem install bundler
- script: bundle install --retry=3 --jobs=4
- script: bundle exec fastlane install_plugins

- script: chmod +x gradlew
- script: bundle exec fastlane build_apk_by_tag
  displayName: Build payhere APK

